publish_mode: editorial_workflow
backend:
  name: github
  repo: nightingalehq/serohub
  open_authoring: true
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: 'studies'
    label: 'Study'
    folder: 'content/studies'
    path: '{{slug}}.md'
    create: true
    fields:
      - label: "Study name"
        name: "title"
        widget: "string"
        required: true
      - label: "Study URL"
        name: "url"
        widget: "string"
        required: false
      - label: "Study info"
        name: study_info
        collapsed: true
        widget: "object"
        fields:
        - label: "Primary research question(s)"
          name: "research_question"
          widget: "markdown"
          minimal: true
          required: false
        - label: "Used Diagnostic test"
          name: "methods_used"
          widget: "markdown"
          minimal: true
          required: false
        - label: "Primary outcomes"
          name: "primary_outcomes"
          widget: "markdown"
          minimal: true
          required: false
        - label: "Funding source(s)"
          name: "funding_sources"
          widget: "markdown"
          minimal: true
          required: false
      - label: "Study values"
        name: study_numbers
        collapsed: true
        widget: "object"
        fields:
        - label: "Study population"
          name: "study_population"
          widget: "number"
          required: false
        - label: "Total population in this area"
          name: "population"
          widget: "number"
          required: false
      - label: "Study key dates"
        name: "study_dates"
        collapsed: true
        widget: "object"
        fields:
        - label: "Sampling start month"
          name: "sample_start"
          widget: "datetime"
          format: "YYYY-MM"
          default: ""
          hint: "Stores the year and month when sampling started"
          required: false
        - label: "Sampling end month"
          name: "sample_end"
          widget: "datetime"
          format: "YYYY-MM"
          default: ""
          hint: "Stores the year and month when sampling has ended / will end"
          required: false
        - label: "Study start"
          name: "study_start"
          widget: "datetime"
          format: "YYYY-MM"
          default: ""
          hint: "Stores the year and month when the study starts"
          required: false
        - label: "Month of first expected results"
          name: "study_first_results"
          widget: "datetime"
          format: "YYYY-MM"
          default: ""
          hint: "Stores the year and month when first results are expected"
          required: false
      - label: "Study Principal Investigator (PI)"
        name: study_pi
        collapsed: true
        widget: "object"
        fields:
        - label: "Name"
          name: "name"
          widget: "string"
        - label: "Institution"
          name: "institution"
          widget: "string"
        - label: "Position at institution"
          name: "role"
          widget: "string"
        - label: "Contact email"
          name: "email"
          widget: "string"
      - label: "Study overview"
        name: "body"
        widget: "markdown"
  - name: 'publications'
    label: 'Publication'
    folder: 'content/publication'
    path: '{{slug}}.md'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Authors"
        name: "authors"
        widget: "list"
        required: false
      - label: "Publication"
        name: "publication"
        widget: "string"
        required: true
      - label: "Publish date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        default: ""
        required: false
      - label: "Short abstract"
        name: "abstract_short"
        widget: "markdown"
        required: false
      - label: "Abstract"
        name: "abstract"
        widget: "markdown"
        required: false
      - label: "Main Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        required: false
      - label: "Thumbnail Image"
        name: "image_preview"
        widget: "image"
        allow_multiple: false
        required: false
      - label: "Code URL"
        name: "url_code"
        widget: "string"
        required: false
      - label: "Dataset URL"
        name: "url_dataset"
        widget: "string"
        required: false
      - label: "PDF URL"
        name: "url_pdf"
        widget: "string"
        required: false
      - label: "Project URL"
        name: "url_project"
        widget: "string"
        required: false
      - label: "Slides URL"
        name: "url_slides"
        widget: "string"
        required: false
      - label: "Video URL"
        name: "url_video"
        widget: "string"
        required: false
      - label: "Additional information"
        name: "body"
        widget: "markdown"
        default: ""
  - name: 'posts'
    label: 'General content'
    folder: 'content/posts'
    path: '{{slug}}.md'
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Author"
        name: "author"
        widget: "string"
        required: true
      - label: "Publish date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:MM:SS"
        required: true
      - label: "Image"
        name: "image"
        widget: "image"
        allow_multiple: false
        required: false     
      - label: "Post"
        name: "body"
        widget: "markdown"
        default: ""
